### ISSUE TITLE
[Bug Report]: Cannot download assignment folders

### ISSUE THREAD

**Issue by RobbeNooyens** [sanjacob/BlackboardSync#118]
### University name

University of Antwerp

### Short name or abbreviation

UA

### Link to Blackboard instance

lms.uantwerpen.be

### Landing URL after logging in

lms.uantwerpen.be/ultra

### Anything else to add?

<img width="900" alt="Screenshot 2023-11-14 at 16 31 22" src="https://github.com/jacobszpz/BlackboardSync/assets/42799452/ae177d1a-5db1-4f46-9ed6-69082b4a098c">

The green folders are downloaded, the red one not

### License

- [X] I agree to follow this project's License

**Comment by jacobszpz** [comment]
Thank you for reaching out, please let me know the following

1. Which version/commit did you use? 
2. Which platform and which release are you using (.exe, .dmg, PyPI, Flatpak, source)?
3. Were any log files generated by this? (Should be in your download folder)
4. General behaviour of the app: does it open the login window multiple times? Is it always downloading? Any other notes?

Hope to solve your issue soon

**Comment by jacobszpz** [comment]
Unfortunately, as of now errors caught in individual files/folders are not handled:

https://github.com/jacobszpz/BlackboardSync/blob/3003acd76cf48d0f3fc7f971414483bb8f8b5f72/blackboard_sync/download.py#L145C13-L157C21

Independent of solving this I will implement logging for this too

**Comment by sanjacob** [comment]
@RobbeNooyens this is now supported
