### ISSUE TITLE
[University Support]: Add support for University of Lincoln

### ISSUE THREAD

**Issue by nashgabs** [sanjacob/BlackboardSync#123]
First of all, thanks for creating this project. It would be great to see my own institution on this list if possible.
Name: ``` University of Lincoln ```
Abbr.: ```UoL```
Portal URL: ```https://blackboard.lincoln.ac.uk/```
Landing URL: ```https://blackboard.lincoln.ac.uk/ultra```
dateSourceID: ```_570_1```

**Comment by sanjacob** [comment]
Please give the uni-of-lincoln branch a test and let me know

**Comment by nashgabs** [comment]
It works exactly as I needed, thank you. No issues to report.
