### ISSUE TITLE
[Bug Report]: Webdav files not downloading

### ISSUE THREAD

**Issue by RobbeNooyens** [sanjacob/BlackboardSync#128]
### BlackboardSync Version

Latest

### BlackboardSync Release

MacOS build

### Operating System and Version

macOS

### University Name

UAntwerpen

### Problem Description

Somehow UAntwerpen formatted specific folders as "Documents" with <a> tags referring to the actual documents. This raises a ValueError in download.py which is not intercepted. Adding a pass for ValueError solves this issue for me:

`        elif res in (BBResourceType.file, BBResourceType.document) and has_changed:
            attachments = []

            try:
                attachments = self._sess.fetch_file_attachments(course_id=course_id,
                                                                content_id=content.id)

            except RequestException:
                self.logger.warn(f"Error while getting attachments for {course_id}")
            except ValueError:
                pass`

Since its probably only a UAntwerpen thing and not applicable for other universities (and might break stuff) I decided to just let you know and make it a pull request.

**Comment by sanjacob** [comment]
Are you using 0.9.11? Or one of the alpha builds? There have been some quick fixes applied since 0.9.11 so it's possible your problem is solved. On the other hand, I am planning on a more substantial upgrade in a few weeks' time. If you are able to give me more insight into your issue that would be appreciated.

**Comment by sanjacob** [comment]
I have included this `except` statement in the last prerelease, but I will keep an eye on this underlying error
