### ISSUE TITLE
[University Support]: University of Minho

### ISSUE THREAD

**Issue by Darguima** [sanjacob/BlackboardSync#144]
Hi, here is the data for University of Minho. I already tried it and it seems be working.

`name`: University of Minho
`short_name`: UM
`start_url`: https://elearning.uminho.pt
`target_url`: https://elearning.uminho.pt/ultra/
`api_url`: https://elearning.uminho.pt

Data sourceIDs is always "_2_1"

**Comment by sanjacob** [comment]
Merged in a770b93b811485ea9a23bfdebece9b027e4c68ba

**Comment by sanjacob** [comment]
Please give it a try and see if there are any issues

**Comment by Darguima** [comment]
It looks perfect!
