### ISSUE TITLE
[New University]: (It is a community college, please let me know if possible)

### ISSUE THREAD

**Issue by jackjack21-pixel** [sanjacob/BlackboardSync#162]
### University name

Schoolcraft College

### Link to Blackboard instance

https://bb.schoolcraft.edu

### Landing URL after logging in

https://bb.schoolcraft.edu/ultra/institution-page

### Valid Blackboard data sources (optional)

_2_1

### License

- [X] I agree to follow this project's License

**Comment by jackjack21-pixel** [comment]
Can I ask when will this be done, sorry asking because my classes end in a few weeks
@sanjacob

**Comment by sanjacob** [comment]
Give me a day or two

**Comment by sanjacob** [comment]
Please test [0.11.2](https://github.com/sanjacob/BlackboardSync/releases/tag/0.11.2) and let me know

**Comment by jackjack21-pixel** [comment]
hey bro, its downloading the folders but not the files itself. Thank you for adding mine though!!
![image](https://github.com/sanjacob/BlackboardSync/assets/121407935/a9a565d6-a90f-412f-8832-5ee5a6e5b96f)

**Comment by sanjacob** [comment]
Can you install via pip instead and run and paste the output here?

**Comment by jackjack21-pixel** [comment]
can you help me install it ☠️ i tried but i dont know how

**Comment by jackjack21-pixel** [comment]
uhh @sanjacob what am i doing wrong haha
![image](https://github.com/sanjacob/BlackboardSync/assets/121407935/0ef7d6b2-050e-4183-879b-fe6726b6948a)

**Comment by sanjacob** [comment]
Try  python3 -m blackboard_sync

**Comment by jackjack21-pixel** [comment]
@sanjacob python 3 is not recognized

**Comment by sanjacob** [comment]
For your cmd to find python you need to register it on the PATH env variable. Even in this output it shows that blackboardsync is not on path. Maybe check whether you can get python or blackboardsync on the PATH var (maybe you need to open cmd again), check also it might be `python` instead.

See this https://realpython.com/add-python-to-path/

**Comment by jackjack21-pixel** [comment]
can you recommend a youtube video? https://www.youtube.com/watch?v=AMAE0S_NzxE this is the one i am following, is it accurate?

**Comment by jackjack21-pixel** [comment]
@sanjacob you there???

**Comment by jackjack21-pixel** [comment]
@sanjacob UPDATE. stuck on fetching courses and still no dcuments
![image](https://github.com/sanjacob/BlackboardSync/assets/121407935/4acdc088-eb2f-410f-aba3-20b9d01c96a3)

**Comment by sanjacob** [comment]
Can you check if there are any log files inside the download folder?

**Comment by jackjack21-pixel** [comment]
![image](https://github.com/sanjacob/BlackboardSync/assets/121407935/1905e817-b2e0-4a59-b914-3ee350a3edb7)
@sanjacob

**Comment by jackjack21-pixel** [comment]
@sanjacob you there?

**Comment by sanjacob** [comment]
> @sanjacob UPDATE. stuck on fetching courses and still no dcuments ![image](https://private-user-images.githubusercontent.com/121407935/318936697-4acdc088-eb2f-410f-aba3-20b9d01c96a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTg3OTgsIm5iZiI6MTcxMjIxODQ5OCwicGF0aCI6Ii8xMjE0MDc5MzUvMzE4OTM2Njk3LTRhY2RjMDg4LWViMmYtNDEwZi1hYmEzLTIwYjlkMDFjOTZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwODE0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTdlNjA4YjQ2YzQ2YTYzNTkwYzI2NTk1MzYxNjRjMDM5ZTM3ZGQ0OTI5M2VmMmZhZTkxYjNmNzNjNGQ0ZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C58BKKSKvmLrTgEvCnUExk_FOIVbxClzMgpmtpqmPT8)

Can you paste the whole output? Thank you (redact whatever you think necessary)

**Comment by jackjack21-pixel** [comment]
@sanjacob 
![image](https://github.com/sanjacob/BlackboardSync/assets/121407935/3e3e651b-e8e3-4dc4-8ade-3deac18b958b)
the entire code https://pastecode.io/s/isrx3upm
please help, thanks!

**Comment by sanjacob** [comment]
Can you confirm any file has been downloaded? There seems to be a few that did get downloaded

**Comment by sanjacob** [comment]
The repeated fetching course is just because it has not found any new files, so that isn't an issue

**Comment by jackjack21-pixel** [comment]
yes only one course was downloaded properly
others havent, what should i do?

**Comment by jackjack21-pixel** [comment]
@sanjacob

**Comment by jackjack21-pixel** [comment]
Can you tell me in detail what do you need..or a solution lol

**Comment by jackjack21-pixel** [comment]
@sanjacob you there?
