### ISSUE TITLE
[Bug Report]: Files not downloading from python or the application

### ISSUE THREAD

**Issue by jackjack21-pixel** [sanjacob/BlackboardSync#169]
### BlackboardSync Version

0.11.2 Latest

### BlackboardSync Release

windows and python

### Python Version

3.11

### Operating System and Version

windows 11

### University Name

schoolcraft college

### Problem Description

hey bro, I am sorry. I wasn't trying to be rude. I think we have a timezone difference thats why my messages come unorganized. Please man, I need this fixed before my class ends, that's why I was tagging you multiple times. Please help.

**Comment by sanjacob** [comment]
I have released a small update which may provide more information about your issue

```bash
pip uninstall blackboardsync
pip install blackboardsync==0.11.3rc1
```

After doing this, run and paste the output here.

**Comment by jackjack21-pixel** [comment]
``Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\****> pip uninstall blackboardsync
Found existing installation: blackboardsync 0.11.2
Uninstalling blackboardsync-0.11.2:
  Would remove:
    c:\users\USERNAME\appdata\roaming\python\python311\scripts\blackboardsync.exe
    c:\users\USERNAME\appdata\roaming\python\python311\site-packages\blackboard_sync\*
    c:\users\USERNAME\appdata\roaming\python\python311\site-packages\blackboardsync-0.11.2.dist-info\*
Proceed (Y/n)? y
  Successfully uninstalled blackboardsync-0.11.2
PS C:\Users\USERNAME> pip install blackboardsync==0.11.3rc1
Defaulting to user installation because normal site-packages is not writeable
Collecting blackboardsync==0.11.3rc1
  Downloading blackboardsync-0.11.3rc1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pyqt5>=5.15.10 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (5.15.10)
Requirement already satisfied: pyqtwebengine>=5.15.6 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (5.15.6)
Requirement already satisfied: beautifulsoup4>=4.12.2 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (4.12.2)
Requirement already satisfied: pydantic>=2.1.1 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (2.6.4)
Requirement already satisfied: pathvalidate>=3.1.0 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (3.2.0)
Requirement already satisfied: python-dateutil==2.8.2 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (2.8.2)
Requirement already satisfied: appdirs==1.4.4 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (1.4.4)
Requirement already satisfied: lxml>=4.7.1 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (4.9.3)
Requirement already satisfied: requests>=2.25.0 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (2.31.0)
Requirement already satisfied: packaging>=23.1 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from blackboardsync==0.11.3rc1) (23.1)
Requirement already satisfied: six>=1.5 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from python-dateutil==2.8.2->blackboardsync==0.11.3rc1) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from beautifulsoup4>=4.12.2->blackboardsync==0.11.3rc1) (2.5)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from pydantic>=2.1.1->blackboardsync==0.11.3rc1) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from pydantic>=2.1.1->blackboardsync==0.11.3rc1) (2.16.3)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from pydantic>=2.1.1->blackboardsync==0.11.3rc1) (4.10.0)
Requirement already satisfied: PyQt5-sip<13,>=12.13 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from pyqt5>=5.15.10->blackboardsync==0.11.3rc1) (12.13.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from pyqt5>=5.15.10->blackboardsync==0.11.3rc1) (5.15.2)
Requirement already satisfied: PyQtWebEngine-Qt5>=5.15.0 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from pyqtwebengine>=5.15.6->blackboardsync==0.11.3rc1) (5.15.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from requests>=2.25.0->blackboardsync==0.11.3rc1) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from requests>=2.25.0->blackboardsync==0.11.3rc1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from requests>=2.25.0->blackboardsync==0.11.3rc1) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\USERNAME\appdata\roaming\python\python311\site-packages (from requests>=2.25.0->blackboardsync==0.11.3rc1) (2023.5.7)
Downloading blackboardsync-0.11.3rc1-py3-none-any.whl (225 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.9/225.9 kB 2.3 MB/s eta 0:00:00
Installing collected packages: blackboardsync
  WARNING: The script blackboardsync.exe is installed in 'C:\Users\USERNAME\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed blackboardsync-0.11.3rc1
PS C:\Users\USERNAME> blackboardsync
blackboardsync : The term 'blackboardsync' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ blackboardsync
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (blackboardsync:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\USERNAME> cd C:\Users\USERNAME\BlackboardSync
PS C:\Users\USERNAME\BlackboardSync> blackboardsync
blackboardsync : The term 'blackboardsync' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ blackboardsync
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (blackboardsync:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\USERNAME\BlackboardSync> python -m blackboard_sync
Loading preexisting configuration
js: Uncaught SyntaxError: Unexpected token '='
js: A cookie associated with a cross-site resource at http://alt-61bced46aed1c.blackboard.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
js: Uncaught SyntaxError: Unexpected token '='
js: Error fetching data: TypeError: AbortSignal.timeout is not a function
js: Attempting to get paged collection at /public/v1/lti/placements without a filter, this might be a performance issue.
js: Invalid 'X-Frame-Options' header encountered when loading 'https://developer.blackboard.com/ltiStorage': '' is not a recognized directive. The header will be ignored.
js: Uncaught SyntaxError: Unexpected token '='
js: A cookie associated with a cross-site resource at http://alt-61bced46aed1c.blackboard.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
js: A cookie associated with a cross-site resource at https://alt-61bced46aed1c.blackboard.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
Logged in successfully
Starting sync thread
Fetching user memberships
Fetching course
<COURSE 1 (2ND 12WK - 01/29) - 111122> - <COURSE 1 (2ND 12WK - 01_29) - 111122>
    Getting Started in COMA 105[BBResourceType.lesson]
    Multicultural Fair Experience[BBResourceType.courselink]
    Quizzes[BBResourceType.folder]
        First Week Quiz[BBResourceType.asmt_test_link]
        Chapter 2 Quiz[BBResourceType.asmt_test_link]
        Chapter 3 Quiz[BBResourceType.asmt_test_link]
        Listening Quiz[BBResourceType.asmt_test_link]
        Nonverbal Communication Quiz[BBResourceType.asmt_test_link]
        Chapter 6 Quiz[BBResourceType.asmt_test_link]
        Chapter 7 Quiz[BBResourceType.asmt_test_link]
    Course Assignments[BBResourceType.folder]
        In-class Activities and Participation[BBResourceType.asmt_test_link]
        Media Review: Assessment 1[BBResourceType.asmt_test_link]
        Research This!: Assessment 2[BBResourceType.asmt_test_link]
        Socratic Seminar: Assessment 3[BBResourceType.asmt_test_link]
        Group Project--Group Essay and Project Grade[BBResourceType.asmt_test_link]
        Group Project Individual Essay[BBResourceType.asmt_test_link]
        Podcast Review: Assessment 5[BBResourceType.asmt_test_link]
    Chapter Notes[BBResourceType.folder]
        firstdayslides105.pptx[BBResourceType.file]
        chapteronewinter2024.pptx[BBResourceType.file]
        chapter2coma105.pptx[BBResourceType.file]
        Media Review/Chapter 8-Culture[BBResourceType.file]
        Chapter3COMA105.pptx[BBResourceType.file]
        coma105listening.pptx[BBResourceType.file]
        COMA105nonverbal.pptx[BBResourceType.file]
        coma105interpersonal.pptx[BBResourceType.file]
        Chapter 6 Emotions[BBResourceType.file]
        Conflict Management[BBResourceType.file]
        Chapter 7 Friendship[BBResourceType.file]
        Chapter 7 Family Communication[BBResourceType.file]
        Chapter 7 Romantic Relationships[BBResourceType.file]
        Chapter 13--Small Group Communication[BBResourceType.file]
Fetching course
<COURSE 2 (01/08) - 115931> - <COURSE 2 (01_08) - 115931>
    Getting Started in Course ###[BBResourceType.lesson]
Fetching course
<COURSE 3 (01/08) - 112731> - <COURSE 3 (01_08) - 112731>
    Getting Started in CIS 129[BBResourceType.lesson]
    Module 1: Overview of Computers and Programming[BBResourceType.lesson]
    Module 2: High Quality Programs[BBResourceType.lesson]
    Module 3: Understanding Structure[BBResourceType.lesson]
    Module 4: Making Decisions[BBResourceType.lesson]
    Unit 1 Exam[BBResourceType.folder]
        Introduction[BBResourceType.folder]
            Introduction[BBResourceType.document]
        Preparing for the Exam[BBResourceType.folder]
Writing to C:\Users\USERNAME\Documents\Biol_238\2024\COURSE 1 (2ND 12WK - 01_29) - 111122\Chapter Notes\COMA105SmallGroup.pptx
            Preparing for the Exam[BBResourceType.document]
        Unit 1 Exam: M1 - M4[BBResourceType.asmt_test_link]
        Unit 1 Exam: Review[BBResourceType.asmt_test_link]
    Module 5: Looping[BBResourceType.lesson]
    Module 6: Arrays[BBResourceType.lesson]
    Module 7: File Handling and Applications[BBResourceType.lesson]
    Module 8: Advanced Data Handling Concepts[BBResourceType.lesson]
    Unit 2 Exam[BBResourceType.folder]
        Unit 2 Exam - Preparing for the Exam[BBResourceType.folder]
            Unit 2 Exam - Preparing for the Exam[BBResourceType.document]
        Unit 2 Exam - Introduction[BBResourceType.folder]
            Unit 2 Exam - Introduction[BBResourceType.document]
        Unit 2 Exam: M5 - M8[BBResourceType.asmt_test_link]
        Unit 2 Exam: Review[BBResourceType.asmt_test_link]
    Module 9: Advanced Modularization Techniques[BBResourceType.lesson]
    Module 10: Object-Oriented Programming[BBResourceType.lesson]
    Module 11: Event-Driven GUI Programming, Multithreading, and Animation[BBResourceType.lesson]
    Unit 3 Exam[BBResourceType.folder]
        Unit 3 Exam - Introduction[BBResourceType.folder]
            Unit 3 Exam - Introduction[BBResourceType.document]
        Unit 3 Exam - Preparing for the Exam[BBResourceType.folder]
            Unit 3 Exam - Preparing for the Exam[BBResourceType.document]
        Unit 3 Exam: M9 - M11[BBResourceType.asmt_test_link]
        Exam 3: Review[BBResourceType.asmt_test_link]
Fetching course
<COURSE 4 (01/08) - 115331> - <COURSE 4 (01_08) - 115331>
    Instructor Info/Welcome[BBResourceType.folder]
        Tamara Wrone, Ph.D.[BBResourceType.document]
    Syllabus/Schedule[BBResourceType.folder]
        Fall 2022 COURSE 4 145426 Syllabus[BBResourceType.document]
    Pearson Mastering COURSE 4 Registration and Course ID[BBResourceType.folder]
        Pearson Mastering COURSE 4 Registration and Course ID[BBResourceType.document]
    Pearson Mastering A&P Link[BBResourceType.externallink]
    Lecture Documents[BBResourceType.folder]
        Lecture Powerpoints[BBResourceType.folder]
            Chapter 19 Lecture PowerPoint[BBResourceType.folder]
                ultraDocumentBody[BBResourceType.document]
            Chapter 20 Part I Lecture PowerPoint[BBResourceType.folder]
                ultraDocumentBody[BBResourceType.document]
            Chapter 20 Part II Lecture PowerPoint[BBResourceType.file]
            Chapter 21 Lecture PowerPoint[BBResourceType.file]
            Chapter 22 Lecture PowerPoint[BBResourceType.file]
            Chapter 23 Part I Lecture PowerPoint[BBResourceType.file]
            Chapter 23 Part II Lecture PowerPoint[BBResourceType.file]
            Chapter 24 Lecture PowerPoint[BBResourceType.file]
            Chapter 25 Lecture PowerPoint[BBResourceType.folder]
                ultraDocumentBody[BBResourceType.document]
            Chapter 26 Lecture PowerPoint[BBResourceType.file]
            Chapter 27 Part I Lecture PowerPoint[BBResourceType.file]
            Chapter 27 Part II Lecture PowerPoint[BBResourceType.file]
            Chapter 28 Lecture PowerPoint[BBResourceType.file]
        Lecture Exam Study Guides[BBResourceType.folder]
            COURSE 4 Lecture Exam 1 Study Guide.docx[BBResourceType.file]
            COURSE 4 Lecture Exam 2 Study Guide.docx[BBResourceType.file]
            COURSE 4 Lecture Exam 3 Study Guide.docx[BBResourceType.file]
            COURSE 4 Lecture Exam 4 Study Guide.docx[BBResourceType.file]
            COURSE 4 Lecture Exam 5 Study Guide.docx[BBResourceType.file]
            COURSE 4 Lecture Exam 6 Study Guide.docx[BBResourceType.file]
        Handouts/Worksheets[BBResourceType.folder]
            Chapter 20 Cardiodynamics Math Worksheet[BBResourceType.folder]
                Chapter 20 Cardiodynamics Math Worksheet[BBResourceType.document]
            Chapter 20 Factors that Influence Cardiodynamics Worksheet[BBResourceType.folder]
                Chapter 20 Factors that Influence Cardiodynamics Worksheet[BBResourceType.document]
            Chapter 25 Cell Respiration Handout[BBResourceType.folder]
                Chapter 25 Cell Respiration Handout[BBResourceType.document]
    Lab Documents[BBResourceType.folder]
        COURSE 4 Microscope Focusing Tips[BBResourceType.file]
        Lab Report (1,5,7,8,10,11) Drawing Instructions[BBResourceType.folder]
            ultraDocumentBody[BBResourceType.document]
        Answers to "Pre-lab" of Lab Reports[BBResourceType.folder]
            Lab 1[BBResourceType.folder]
                Lab 1[BBResourceType.document]
            Lab 3[BBResourceType.folder]
                Lab 3[BBResourceType.document]
            Lab 4[BBResourceType.folder]
                Lab 4[BBResourceType.document]
            Lab 5[BBResourceType.folder]
                Lab 5[BBResourceType.document]
            Lab 6[BBResourceType.folder]
                Lab 6[BBResourceType.document]
            Lab 7[BBResourceType.folder]
                Lab 7[BBResourceType.document]
            Lab 8[BBResourceType.folder]
                Lab 8[BBResourceType.document]
            Lab 9[BBResourceType.folder]
                Lab 9[BBResourceType.document]
            Lab 10[BBResourceType.folder]
                Lab 10[BBResourceType.document]
            Lab 11[BBResourceType.folder]
                Lab 11[BBResourceType.document]
        Lab 7 Documentary Video Link: PBS NOVA: "Vaccines: Calling the Shots" (2014)[BBResourceType.externallink]
        Lab Exam 1[BBResourceType.folder]
            COURSE 4 Lab Exam 1 Study Guide[BBResourceType.folder]
                COURSE 4 Lab Exam 1 Study Guide[BBResourceType.document]
        Lab Exam 2[BBResourceType.folder]
            Lab Exam 2: Chapter 21: Arteries and Veins Lecture Powerpoint[BBResourceType.folder]
                Lab Exam 2: Chapter 21: Arteries and Veins Lecture Powerpoint[BBResourceType.document]
            Lab Exam 2 Handout[BBResourceType.folder]
                Lab Exam 2 Handout[BBResourceType.document]
        Lab Exam 3[BBResourceType.folder]
            COURSE 4 Digestive, Lymphatic, & Respiratory Lab Exam 3 Handout[BBResourceType.folder]
                COURSE 4 Digestive, Lymphatic, & Respiratory Lab Exam 3 Handout[BBResourceType.document]
        Lab Exam 4[BBResourceType.folder]
            COURSE 4 Lab Exam 4 Study Guide[BBResourceType.folder]
                ultraDocumentBody[BBResourceType.document]
    Top Tips to Succeed in this Course[BBResourceType.folder]
        Top Tips to Succeed in this Course[BBResourceType.document]
    Crash Course Anatomy & Physiology YouTube Videos Link (fun!!)[BBResourceType.externallink]
    COURSE 4 Meeting Zoom Link[BBResourceType.externallink]
Fetching course
Fetching course
Fetching course
Fetching course
Fetching course
Fetching course
Fetching course
Fetching course
Fetching course
Fetching course
Fetching course
`

`

same issue with the fetching courses

**Comment by sanjacob** [comment]
I don't think you deleted the right file, it seems that the script only downloaded new files. For reference, it should be a file named "blackboard_sync", I think it has no extension. To get out of doubt, just check the contents of either the file you deleted or the new one that should have been created in its place, and paste them here.

I still don't know what is going wrong tbh.

**Comment by sanjacob** [comment]
Also check again if any new logs are available

**Comment by jackjack21-pixel** [comment]
@sanjacob which one should i do this time.. No logs
![image](https://github.com/sanjacob/BlackboardSync/assets/121407935/d98661a0-1e85-4f4f-9579-2ca3ec98c23e)

**Comment by jackjack21-pixel** [comment]
can i delete all of them so there's no problem lol

**Comment by sanjacob** [comment]
Last one, only that one

**Comment by jackjack21-pixel** [comment]
@sanjacob you are gonna be so mad lmao, i was selecting download files from 2022. That's why it wasn't downloading 😭😭😭. My bad for wasting your time!!!

**Comment by sanjacob** [comment]
For cases when you need older files, you can just tick the checkbox that says 'all files'. But I'm not completely sure it was that, since you would at least have files from Aug 2022-Aug 2024 (approx). If you need to re-do the setup you can just choose that option by right clicking the system tray, but files will be redownloaded (without overwriting other files).

Right now I do have an improvement for the download module in the queue but it might take more time for me to have time to finalise it.
