### ISSUE TITLE
[University Support]: Griffith University

### ISSUE THREAD

**Issue by KR3dwood** [sanjacob/BlackboardSync#171]
Hello, 
I'd like to add support for Blackboard Sync for Griffith University, Australia. Details are as follows:

**University name:** Griffith University

**Short name or abbreviation:** GriffUni

**Link to Blackboard portal:** http://bblearn.griffith.edu.au/

**Landing URL after successfully logging in:** https://bblearn.griffith.edu.au/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_1_1

And is there an ETA on the next release? :)

Kind regards,
Kristina
Learning and Teaching Solutions
Griffith University

**Comment by KR3dwood** [comment]
Also - is there a potential ETA on the next release? :)

**Comment by sanjacob** [comment]
Please try out [this pre-release](https://github.com/sanjacob/BlackboardSync/releases/tag/0.11.4-alpha.1) and let me know if there are any issues

**Comment by KR3dwood** [comment]
I'm getting a message that I don't have permissions to run the file... :/
I've tried activating admin permissions on my PC, so it's definitely not that (I was able to run the regular release)

**Comment by sanjacob** [comment]
@KR3dwood if you are on a university-managed device, it may be that you are restricted from executing internet downloads, and you should consider getting help from the IT department. If it is your personal machine, then maybe you can provide me with the exact error message that you are seeing and I'll try to help you. But there is no difference between a pre-release and a regular release other than the name.

**Comment by KR3dwood** [comment]
@sanjacob we managed to get the pre-release installed, but what we're downloading from our Blackboard instance (with a student user) doesn't appear to be what is shown in a full release... :/ it's not a full export of all of their course files. It's just one or two.

Any news on when a full release will be available? :)

**Comment by sanjacob** [comment]
Unfortunately that depends on your specific Blackboard instance. You could have someone from the CS department help you debug this, or if you prefer I can debug it myself if you have the ability to create a test user for me solely for this task.
The pre-release is helpful to find bugs such as these and fix them before doing an official release, but ultimately has no intrinsic qualities that would make its behaviour any different, other than the fixes we can perform thanks to testing the pre-release.

**Comment by sanjacob** [comment]
It's also worth checking the logs directory inside your download folder (if it exists), as it may help show any errors that ocurred during the download process

**Comment by KR3dwood** [comment]
Hi Jacob, 
one of our platform engineers had a look and has passed on the following:

This is the error he gets during the process of exporting data from Blackboard - 
![image](https://github.com/sanjacob/BlackboardSync/assets/166570143/8142a847-a2e3-4293-bbd0-48f7e16a4472)

The process almost immediately stalls/hangs straight after this trying to write the next file:
![MicrosoftTeams-image (23)](https://github.com/sanjacob/BlackboardSync/assets/166570143/efd31c47-7374-4302-8205-96aaa00f3e20)

He's asking whether it's possible to add a try-catch block in the code so that we don't get any unhandled exceptions ?

:)

**Comment by sanjacob** [comment]
Thank you for the reply, this is really helpful in finding out why you are experiencing issues. While I will need time to look at it in detail, right away it seems it might be that the path is too long for windows. Since the path is constructed from your course and content names, this only becomes a problem with long names.
This could be further confirmed if you can try installing the app on either Mac OS or Linux, but it's not completely necessary. I'll take a deeper look into it soon and probably come up with an alternative strategy for cases like this one.

**Comment by sanjacob** [comment]
I have opened #178 for further discussion of this issue.
