### ISSUE TITLE
Fix Windows file path length limitation

### ISSUE THREAD

**Issue by sanjacob** [sanjacob/BlackboardSync#178]

**Comment by KR3dwood** [comment]
Hi Jacob, have there been any further developments on another pre-release for us to test?

**Comment by sanjacob** [comment]
> Hi Jacob, have there been any further developments on another pre-release for us to test? We are approaching our decommission date for Blackboard, so the matter is becoming somewhat urgent :/

We don't do rushing here unfortunately. You can contact Blackboard directly to see what solution they give you, as I assume they charge plenty for their services.

**Comment by sanjacob** [comment]
Currently this is somewhat big of a change, so probably won't include it for now until I rework the download module to simplify things. In the meantime, you can manually change the path limitation on your machine and then report back.

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

Or you can try using mac or Linux.

**Comment by sanjacob** [comment]
Possible fix

https://github.com/google/tensorstore/blob/1a0135b6df1464a4d4cc1960c43422c2b25f9b92/docs/doctest_test.py#L85
