### ISSUE TITLE
[University Support]: University of Pretoria

### ISSUE THREAD

**Issue by whipped-cream** [sanjacob/BlackboardSync#183]
Hello, here is the data for the University of Pretoria

**University name:** University of Pretoria

**Short name or abbreviation:** UP

**Link to Blackboard portal:** https://clickup.up.ac.za

**Landing URL after successfully logging in:** https://clickup.up.ac.za/ultra

I have tested this on my machine and it does download the content.

The university is in Africa if you want to add it to the supported universities list

Thanks

**Comment by whipped-cream** [comment]
I'm noticing now that UP is already taken so probably no short name rather

**Comment by sanjacob** [comment]
The short name is only for searching when selecting it for the first time, so no problem there. I will do this along with the other fix.
