### ISSUE TITLE
[Bug Report]: UI limits maximum year to download from to 2023

### ISSUE THREAD

**Issue by whipped-cream** [sanjacob/BlackboardSync#184]
### BlackboardSync Version

ecae7bfc82c046cb68c8130a7cad272bc9104265

### BlackboardSync Release

From source

### Python Version

Python 3.11

### Operating System and Version

Linux 6.6.30-2-lts

### University Name

University of Pretoria

### Problem Description

The UI limits the download year to be from 2023 or before meaning I cannot download only the present year's content. Changing the maximum value to 2024 in qt/SetupWizard.ui seems to make it work as expected.

**Comment by sanjacob** [comment]
That's true, probably better to set it to the current year regardless. I thought I'd get around to it but I forgot. If you want to make a PR let me know otherwise Ill make one tomorrow.
