### ISSUE TITLE
[University Support]: Texas Tech University

### ISSUE THREAD

**Issue by kktrum** [sanjacob/BlackboardSync#197]
- University name: Texas Tech University
- Short name or abbreviation: TTU
- Link to Blackboard portal: https://ttu.blackboard.com/
- Landing URL after successfully logging in: https://ttu.blackboard.com/ultra/institution-page

**Comment by sanjacob** [comment]
I'm having trouble reaching the site, is it region-restricted?

**Comment by sanjacob** [comment]
Perhaps a DNS issue
