### ISSUE TITLE
Latest Exe: With UoM

### ISSUE THREAD

**Issue by d-dahir** [sanjacob/BlackboardSync#248]
Hi,

Thank you for adding UoM support. Please could you provide a new .exe with the University of Manchester included?

Thanks!

**Comment by sanjacob** [comment]
will do

**Comment by sanjacob** [comment]
Give it a try:

https://github.com/sanjacob/BlackboardSync/releases/download/0.11.5-alpha.7/BlackboardSync-0.11.5-alpha.7.exe
