### ISSUE TITLE
Pausing when running / Not starting

### ISSUE THREAD

**Issue by jrh03** [sanjacob/BlackboardSync#294]
### BlackboardSync Version

v0.11.2 and v0.12.0 alpha3

### BlackboardSync Release

MacOS release and Source

### Python Version

Python 3.12

### Operating System and Version

macOS

### University Name

Cardiff University

### Problem Description

I’ve had two seperate issues.

With the MacOS release, I was mostly just getting constant log files created with nothing happening. 

The log file was (note that this isn’t fully exact as I’m copying from a message previously sent)
`Exception in sync thread
Traceback (most recent call last):
  File "blackboard_sync/sync.py", line 173, in _sync_task
  File "blackboard_sync/download.py", line 246, in download
  File "blackboard_sync/blackboard/api.py", line 114, in get_wrapper
ValueError: Server responded with an error code `

In the most recent alpha, it will install some files from a recent module but then stop completely. From running in the command line I believe it says that status handlers takes two arguments but received three. I can provide better logs later if necessary. 

Have tried a few remedies, like connecting to Uni VPN and using email vs student id to log in but nothing seems to be working sadly.

**Comment by sanjacob** [comment]
Please delete the configuration file located in `~/Library/Application Support/blackboard_sync`, then download and test `package-macos-latest` from the artifacts section here:
https://github.com/sanjacob/BlackboardSync/actions/runs/10447365294

This should correct the status handler error you are seeing, but most likely will continue to throw an error and stop.
However, this should let us know what error the server returns.

**Comment by jrh03** [comment]
I'm not sure if I maybe deleted too much, as I just used rm on the location for the configuration file,  but there now seems to be an initialising error of some kind, I think? The package would simply open and close so I cloned the branch and this is the error I'm now getting


```
Initialising BlackboardSync
Loading preexisting configuration
Traceback (most recent call last):
  File "/Users/your-username/.asdf/installs/python/3.10.12/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/Users/your-username/.asdf/installs/python/3.10.12/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/__main__.py", line 32, in <module>
    raise SystemExit(main())

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/__main__.py", line 27, in main
    BBSyncController()

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/sync_controller.py", line 68, in __init__
    OSUtils.add_to_startup()

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/qt/qt_elements.py", line 112, in add_to_startup
    settings = QSettings(str(plist_path), QSettings.NativeFormat)

AttributeError: type object 'QSettings' has no attribute 'NativeFormat'
```


I could potentially be running the code wrong as I have attempted to run it in my IDE to try and see what the issue was but I can't tell.

**Comment by sanjacob** [comment]
That is indeed just a fault with the source code, due to the transition to PyQt6. I'll fix it within a few minutes.
The reason why you are only seeing it now is because you deleted the configuration file, therefore having to go through the setup process again. In this case it is the function that enables the program to start at boot.

**Comment by jrh03** [comment]
I installed another release to recreate the config file, this is now the error I'm seeing:

```
Exception in thread Thread-2 (_sync_task):
Traceback (most recent call last):

  File "/Users/your-username/.asdf/installs/python/3.10.12/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()

  File "/Users/your-username/.asdf/installs/python/3.10.12/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/sync.py", line 158, in _sync_task
    job_start_time = self._download.download()

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/download.py", line 110, in download
    Course(course, job).write(self.download_location, self.executor)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/content/course.py", line 32, in __init__
    self.children.append(Content(content, api_path, job))

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/content/content.py", line 36, in __init__
    self.handler = Handler(content, api_path, job)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/content/folder.py", line 22, in __init__
    content.Content(child, {'content_id': child.id, 'course_id': course_id}, job)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/content/content.py", line 36, in __init__
    self.handler = Handler(content, api_path, job)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/content/folder.py", line 22, in __init__
    content.Content(child, {'content_id': child.id, 'course_id': course_id}, job)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/content/content.py", line 36, in __init__
    self.handler = Handler(content, api_path, job)

  File "/Users/your-username/Documents/BlackboardSync/blackboard_sync/content/document.py", line 22, in __init__
    attachments = job.session.fetch_file_attachments(**api_path)

  File "/Users/your-username/.local/share/virtualenvs/BlackboardSync-0fSKxJqE/lib/python3.10/site-packages/tiny_api_client/__init__.py", line 273, in request_wrapper
    response = make_api_call(method, self, endpoint, **kwargs)

  File "/Users/your-username/.local/share/virtualenvs/BlackboardSync-0fSKxJqE/lib/python3.10/site-packages/tiny_api_client/__init__.py", line 206, in make_api_call
    endpoint_response = _handle_response(

  File "/Users/your-username/.local/share/virtualenvs/BlackboardSync-0fSKxJqE/lib/python3.10/site-packages/tiny_api_client/__init__.py", line 179, in _handle_response
    status_handler(status_code, endpoint_response)

  File "/Users/your-username/.local/share/virtualenvs/BlackboardSync-0fSKxJqE/lib/python3.10/site-packages/blackboard/exceptions.py", line 39, in status_handler
    raise BBBadRequestError()

blackboard.exceptions.BBBadRequestError
```

**Comment by sanjacob** [comment]
So that means for some reason when fetching the file attachments for that specific course and content the server is responding with a 400 bad request http error.

I have released an update of the `bblearn` package that will include the response body when throwing an exception, so please update `bblearn` to v0.3.3 and then paste the output here.

Of course, I will still make sure to handle these errors in a more safe manner, but it's also important to check what is going wrong.

**Comment by jrh03** [comment]
This is what is happening before the stack trace:
`Reading Lists[BBResourceType.Other]
Fetching user course <_417261_1>
<23/24-CM3112 Artificial Intelligence> - <23_24-CM3112 Artificial Intelligence>
PhD projects[BBResourceType.Folder]
COMSC General Studentship Scheme[BBResourceType.Folder]
ultraDocumentBody[BBResourceType.Document]
Exception in thread Thread-1 (_sync_task):`

This is the error message:

`blackboard.exceptions.BBBadRequestError: {'status': 400, 'message': 'The Content Item does not support file attachments'}`

I'm not sure what the content item being requested is though.

**Comment by sanjacob** [comment]
I have added an except clause to prevent any errors from spreading upwards.

Can you test this build and see if you face any other issues?
https://github.com/sanjacob/BlackboardSync/actions/runs/10454881846

**Comment by jrh03** [comment]
I think having the self.handler in the try clause is causing issues with this section:

```
        if self.handler.create_dir or self.body:
            path.mkdir(exist_ok=True, parents=True)
```

This is the error:
````
blackboard_sync/content/content.py", line 55, in write
    if self.handler.create_dir or self.body:
AttributeError: 'Content' object has no attribute handler
````

**Comment by sanjacob** [comment]
This build should fix that issues:
https://github.com/sanjacob/BlackboardSync/actions/runs/10455977520

Thanks for the quick replies as well

**Comment by jrh03** [comment]
I think I have now identified which sections are causing the issues. Some folders are stored in a weird/different folder structure which counts completion rate etc. I have attached an image of the sections causing issues.

The fixes introduced have worked for every folder that isn't in these sections, which means that for some courses I have all content, but not for all of them.

<img width="1041" alt="image" src="https://github.com/user-attachments/assets/1e8b91fa-166d-448d-910e-d005a1c2cc25">

**Comment by sanjacob** [comment]
I see, I have never seen this type of content before so it must be relatively new. We will need further efforts to support this.

However, can you confirm that there are no more exceptions thrown (i.e. the download job finishes gracefully)? You will know when clicking on the status bar icon: the last download time will be set to some concrete timestamp.

**Comment by sanjacob** [comment]
Now that I think about it, it may be that this content is only found within the body, which is not checked unless there is a valid handler. Maybe you can check if this is the case, by printing the value of content.body before the content is ignored

**Comment by jrh03** [comment]
I was having a look at it, it's a different type of content class called a lesson. This is what is returned when cycling through 
`for content in contents`

```
4 = {BBCourseContent} BBCourseContent(id='_7684610_1', title='Learning Materials', body=None, created=datetime.datetime(2023, 11, 10, 20, 29, 4, 750...336_1', rel='alternate', title='User Interface View', type='text/html')], hasGradebookColumns=False, hasAssociatedGroups=False)
 availability = {BBAvailability} BBAvailability(available=<BBAvailable.Yes: 'Yes'>, allowGuests=True, adaptiveRelease={}, duration=None)
 body = {NoneType} None
 contentHandler = {BBContentHandler} BBContentHandler(id=<BBResourceType.Lesson: 'x-bb-lesson'>, url=None, file=None, gradeColumnId=None, groupContent=None, targetId=None, targetType=None, placementHandle=None, assessmentId=None, proctoring=None)
 created = {datetime} datetime.datetime(2023, 11, 10, 20, 29, 4, 750000, tzinfo=TzInfo(UTC))
 hasAssociatedGroups = {bool} False
 hasChildren = {bool} True
 hasGradebookColumns = {bool} False
 id = {str} '_7684610_1'
 launchInNewWindow = {bool} True
 links = {list: 1} [BBLink(href='/ultra/redirect?redirectType=nautilus&courseId=_417261_1&contentId=_7684610_1&parentId=_7097336_1', rel='alternate', title='User Interface View', type='text/html')]
 model_computed_fields = {dict: 0} {}
 model_config = {dict: 1} {'frozen': True}
 model_extra = {NoneType} None
 model_fields = {dict: 15} {'availability': FieldInfo(annotation=Union[BBAvailability, NoneType], required=False, default=None), 'body': FieldInfo(annotation=Union[str, NoneType], required=False, default=None), 'contentHandler': FieldInfo(annotation=Union[BBContentHandler, NoneType], required=False, default=None), 'created': FieldInfo(annotation=Union[datetime, NoneType], required=False, default=None), 'hasAssociatedGroups': FieldInfo(annotation=bool, required=False, default=False), 'hasChildren': FieldInfo(annotation=bool, required=False, default=False), 'hasGradebookColumns': FieldInfo(annotation=bool, required=False, default=False), 'id': FieldInfo(annotation=str, required=True), 'launchInNewWindow': FieldInfo(annotation=bool, required=False, default=False), 'links': FieldInfo(annotation=list[BBLink], required=False, default=[]), 'modified': FieldInfo(annotation=Union[datetime, NoneType], required=False, default=None), 'parentId': FieldInfo(annotation=Union[str, NoneType], required=False, default=None), 'posi...
 model_fields_set = {set: 12} {'availability', 'contentHandler', 'created', 'hasChildren', 'id', 'launchInNewWindow', 'links', 'modified', 'parentId', 'position', 'reviewable', 'title'}
 modified = {datetime} datetime.datetime(2024, 4, 18, 10, 45, 10, 494000, tzinfo=TzInfo(UTC))
 parentId = {str} '_7097336_1'
 position = {int} 4
 reviewable = {bool} False
 title = {str} 'Learning Materials'
 title_path_safe = {str} 'Learning Materials'
```

I'm not very familiar with the code base nor how the API works but I've been looking at it to see if there's any simple ways to create a class for this content type.

**Comment by sanjacob** [comment]
So it's the same type of content as Folder, basically, with a few differences. We could try to let the Folder class handle it and see if there are any issues.

The codebase is pretty straightforward, all the content handler classes are inside `blackboard_sync/content`, with the base handler being `content.py`. So first you can try modifying that file (the function `get_handler`) to assign Folder to the lesson class. If that doesnt work, make a copy of the Folder class that is better suited for the lesson type.

**Comment by jrh03** [comment]
I was gonna create a PR, but it honestly is as simple as including lessons in the folders.  When I still saw errors showing, I assumed there was more to do, but just letting it run turned out fine.
All that needs to change is this line:
`            case BBResourceType.Folder | BBResourceType.Lesson:`

Errors still pop as lessons have some content which is just text not in a file and directories are still created for these even if nothing is in the directory. 

I also had some timeout errors for some course specific things, I think they tried to follow URLs to some of my lecturers, but that doesn't seem to impact much as far as I can tell.

**Comment by sanjacob** [comment]
That's great news. Thanks a lot for all your help!

**Comment by sanjacob** [comment]
> which is just text not in a file

What type of content is this included in?

> I also had some timeout errors

Maybe you can include some of the output here to see if there's anything we can do about it.

**Comment by jrh03** [comment]
Hi, I had some spare time tonight and also realised some content still wasn't working properly. I'm not sure if this will be common but my lecturers have been uploading PDF's in what I think are ultra document bodies or just documents. When this document returns it has no attachments according to the API but if you check the body you can find PDF's in anchor tags.

If you want to check the branch "learn-handling" in my fork- I have implemented something which allows this to work, however I think it is messy and could be implemented better. The file "attachment_anchors" was also mostly generated by AI. 

Here is a screenshot of the outcome of this- note that the path is too complex.

![image](https://github.com/user-attachments/assets/63d42943-edf5-45af-b8d5-62ea1da3b1d4)

Previously I wouldn't have had access to these PDF's.

I can show you what the content body (the anchor tags) looks like if you are interested however I'm not sure if I should publicly post this.

Also, as an example this is what those pages load like on Blackboard:
![image](https://github.com/user-attachments/assets/680b1301-c40f-4f8a-9573-1cf3b5ff9c0b)
![image](https://github.com/user-attachments/assets/e5b3795b-4da7-4959-a0ed-abd8598f1710)

**Comment by sanjacob** [comment]
@jrh03 Hi there, yes this behaviour is commonplace (including links inside bodies). Blackboard Sync is supposed to parse the body and search for links, then download the files. This behaviour is described in content/body.py and content/webdav.py. There must be a reason why this is not happening in your case. But I suggest starting by debugging the behaviour of body.py to check that the links are detected correctly at least.

**Comment by sanjacob** [comment]
Let's continue this in #314

**Comment by sanjacob** [comment]
@jrh03 I was thinking we could try supporting x-bb-assignment content. Is there any way you can see how they are structured? Thank you

**Comment by sanjacob** [comment]
@jrh03 I have added x-bb-assignment support now, let me know if it does solve some of your issues
