### ISSUE TITLE
[Bug Report]: WebDav parsing may not work in some circumstances

### ISSUE THREAD

**Issue by sanjacob** [sanjacob/BlackboardSync#314]
### BlackboardSync Version

/*

### BlackboardSync Release

/*

### Python Version

/*

### Operating System and Version

/*

### University Name

/*

### Problem Description

As described by @jh

**Comment by sanjacob** [comment]
@jrh03 I suggest you look at this file which I use to manually verify the download job is working as expected. Please let me know how to adjust this so it better reflects reality.

https://github.com/sanjacob/api.bbsync.app/blob/main/learn/api/public/v1/courses/COC001/contents/materials/children.json

**Comment by jrh03** [comment]
I'm gonna start looking through why the content.body isn't being parsed as expected. The link you've attached brings me to a 404 page sadly so I currently can't look at it.

**Comment by sanjacob** [comment]
@jrh03 sorry I forgot it was a private repo, will make it public later

**Comment by sanjacob** [comment]
@jrh03 Since you confirmed this was due to your configuration, I will close this. If you find this to break again, please let me know.
