### ISSUE TITLE
[New University]: Shiv Nadar University

### ISSUE THREAD

**Issue by depleur** [sanjacob/BlackboardSync#316]
### University name

Shiv Nadar University

### University abbreviation

SNU

### Country

India

### URL of university Blackboard instance

https://blackboard.snu.edu.in/

### URL after logging in

https://blackboard.snu.edu.in/ultra/

### License

- [X] I agree to follow this project's License

**Comment by sanjacob** [comment]
Hi there, sorry for the delay, been working on new features to improve the application.

One of these features is automated university detection by internet service provider.

If you have the chance, please visit this website from a device within the university:

https://74mxmsvvgqw6t23xycgaauf3cy0vyncw.lambda-url.eu-west-2.on.aws/

It is an automated ISP checker, just paste the results inside a comment.

Thanks for your help!

**Comment by depleur** [comment]
{"rdapConformance":["history_version_0","nro_rdap_profile_0","cidr0","rdap_level_0"],"notices":[{"title":"Source","description":["Objects returned came from source","APNIC"]},{"title":"Terms and Conditions","description":["This is the APNIC WHOIS Database query service. The objects are in RDAP format."],"links":[{"value":"https://rdap.apnic.net/ip/103.27.164.0/22","rel":"terms-of-service","href":"http://www.apnic.net/db/dbcopyright.html","type":"text/html"}]},{"title":"Whois Inaccuracy Reporting","description":["If you see inaccuracies in the results, please visit: "],"links":[{"value":"https://rdap.apnic.net/ip/103.27.164.0/22","rel":"inaccuracy-report","href":"https://www.apnic.net/manage-ip/using-whois/abuse-and-spamming/invalid-contact-form","type":"text/html"}]}],"country":"IN","events":[{"eventAction":"registration","eventDate":"2013-07-04T08:32:03Z"},{"eventAction":"last changed","eventDate":"2024-08-20T09:15:33Z"}],"name":"SNU","remarks":[{"description":["Shiv Nadar Institution of Eminence Deemed to be University"],"title":"description"}],"links":[{"value":"https://rdap.apnic.net/ip/103.27.164.0/22","rel":"self","href":"https://rdap.apnic.net/ip/103.27.164.0/22","type":"application/rdap+json"},{"value":"https://rdap.apnic.net/ip/103.27.164.0/22","rel":"related","href":"https://netox.apnic.net/search/103.27.164.0%2F22?utm_source=rdap&utm_medium=result&utm_campaign=rdap_result","type":"text/html"}],"status":["active"],"type":"ALLOCATED PORTABLE","endAddress":"103.27.167.255","ipVersion":"v4","startAddress":"103.27.164.0","objectClassName":"ip network","handle":"103.27.164.0 - 103.27.167.255","entities":[{"roles":["technical","administrative"],"events":[{"eventAction":"registration","eventDate":"2017-04-17T06:33:29Z"},{"eventAction":"last changed","eventDate":"2017-04-17T06:33:29Z"}],"links":[{"value":"https://rdap.apnic.net/ip/103.27.164.0/22","rel":"self","href":"https://rdap.apnic.net/entity/SNU1-AP","type":"application/rdap+json"}],"vcardArray":["vcard",[["version",{},"text","4.0"],["fn",{},"text","Shiv Nadar University"],["kind",{},"text","group"],["adr",{"label":"Shiv Nadar University, Village Chithera, Tehsil Dadri,"},"text",["","","","","","",""]],["tel",{"type":"voice"},"text","+91 1203819105"],["email",{},"text","deepak.agrawal@snu.edu.in"]]],"objectClassName":"entity","handle":"SNU1-AP"},{"roles":["abuse"],"events":[{"eventAction":"registration","eventDate":"2014-11-27T06:28:01Z"},{"eventAction":"last changed","eventDate":"2017-04-17T06:37:40Z"}],"links":[{"value":"https://rdap.apnic.net/ip/103.27.164.0/22","rel":"self","href":"https://rdap.apnic.net/entity/IRT-SNU-IN","type":"application/rdap+json"}],"vcardArray":["vcard",[["version",{},"text","4.0"],["fn",{},"text","IRT-SNU-IN"],["kind",{},"text","group"],["adr",{"label":"Shiv Nadar University, Village Chithera, Tehsil Dadri,"},"text",["","","","","","",""]],["email",{},"text","deepak.agrawal@snu.edu.in"],["email",{"pref":"1"},"text","abuse@snu.edu.in"]]],"objectClassName":"entity","handle":"IRT-SNU-IN"}],"cidr0_cidrs":[{"v4prefix":"103.27.164.0","length":22}],"port43":"whois.apnic.net"}

Thanks for reaching out! These are the results.

**Comment by sanjacob** [comment]
Please test either `package-macos-12` (x86_64), `package-macos-14` (arm64), or `package-windows-latest`:
https://github.com/sanjacob/BlackboardSync/actions/runs/10746226939

Let me know if everything seems fine

**Comment by depleur** [comment]
@sanjacob Looks good. Some attached files don't get downloaded, HTML files are downloaded instead.

**Comment by sanjacob** [comment]
@depleur Can you provide an example? Also, please check the `log` folder inside the download location and copy any logs if needed.

**Comment by depleur** [comment]
@sanjacob Sure. So I have this course called Introduction to Data Science for Business Using R and Python, in which I have a folder titled PROJECTS. Inside PROJECTS is a folder called MP1 (shown below). 
![CleanShot 2024-09-07 at 17 25 06@2x](https://github.com/user-attachments/assets/60aa7ca3-4b19-410d-a8a2-8391364d21af)
This has another nested folder called MP1 (shown below).
![CleanShot 2024-09-07 at 17 21 51@2x](https://github.com/user-attachments/assets/b8bf5cfa-192f-4d65-a5da-33c29a2acd4d)
You can look at the path bar to make sense of what I am talking about.
The HTML files look like this:
![CleanShot 2024-09-07 at 17 41 51@2x](https://github.com/user-attachments/assets/ecbfaf97-b374-4bae-b0ac-a35414237d70)
However, the files that accompany this text shown in the HTML are missing from what BBSync downloaded. The original Blackboard location looks like this (First MP1 folder):
![CleanShot 2024-09-07 at 17 38 00@2x](https://github.com/user-attachments/assets/65efd61a-23d7-4431-a4ff-fe29bde8f470) 
Nested MP1 folder:
![CleanShot 2024-09-07 at 17 38 08@2x](https://github.com/user-attachments/assets/39a986f5-612d-4905-9397-527846d1dc3c)
So, essentially, Serve.xlsx and MP1specs.pdf are missing.

**Comment by sanjacob** [comment]
@depleur Please try this new release, but first:
1. Delete your configuration file (otherwise old content won't be downloaded again).
   This is located in Library/Application Support/blackboard_sync
2. Delete (or move) your current sync directory.

Find the downloads here:
https://github.com/sanjacob/BlackboardSync/actions/runs/10754013654

**Comment by depleur** [comment]
@sanjacob Works now, thank you so much for the fix!

**Comment by sanjacob** [comment]
@depleur No problem, glad it works
