### ISSUE TITLE
Feature Request: Option to Remove Dock Icon

### ISSUE THREAD

**Issue by depleur** [sanjacob/BlackboardSync#344]
Since the app works mostly in the background, it would be helpful to have the dock icon removed, leaving just the menubar icon while the app is running. It would help get rid of the clutter.

**Comment by sanjacob** [comment]
Sure, I looked into it and it's a matter of setting `LSUIElement` to `true` in the Info.plist.
However, this is handled by PyInstaller and since there is no flag for it, I will have to rework the build process a little bit, but expect an update in a few days.
