### ISSUE TITLE
[New University]: Humber Polytechnic

### ISSUE THREAD

**Issue by ColeAnthonyCapilongo5735** [sanjacob/BlackboardSync#361]
### University name

Humber College Institute of Technology and Advanced Learning

### University abbreviation

Humber Polytechnic

### University country

Canada

### URL of university Blackboard instance

https://learn.humber.ca

### URL after logging in

https://learn.humber.ca/ultra

### University network information

Name: HUMBERCXNET1
Description: missing
Country: _

### License

- [X] I agree to follow this project's License

**Comment by sanjacob** [comment]
@ColeAnthonyCapilongo5735 Thanks for your help!
Your university should now supported. You will need to wait a few days/week for another release.

If you don't mind me asking, how did you hear about Blackboard Sync?

**Comment by ColeAnthonyCapilongo5735** [comment]
Thanks! A new release would definitely be appreciated.

I'm not exactly sure how I found the project. I was probably just searching for Blackboard downloaders.
