### ISSUE TITLE
[Bug Report]: cannot auto login after installed 0.17.0

### ISSUE THREAD

**Issue by ziyuanding** [sanjacob/BlackboardSync#387]
### BlackboardSync Version

0.17.0

### BlackboardSync Release

by downloading Blackboard.Sync-0.17.0.exe from github release page and install

### Operating System and Version

Windows 10 22H2 19045.4894

### University Name

University of Western Australia

### Problem Description

after received the update notification, I installed this latest version 0.17.0. However, I need to login every time I reopen this program.  i guess cookie is not being correctly stored?  

I don't think there is any changes happened on the LMS side as the old version of BBSync (0.11.2) could still work today, the only reason I moved to 0.17.0 is I cannnot find a way to disable the update notification.
![image](https://github.com/user-attachments/assets/686ff8ee-3e51-4804-8e5a-0f28413959ff)

### Log File Contents

the log file is empty.

**Comment by sanjacob** [comment]
The reason might be because of the update to Qt 6, as the cookie is not and was never manually stored by the app. I will see if there is a way to fix it.

Unfortunately there isn't a way to disable the notification in the app (maybe you can block all of our notifications on windows permissions).

**Comment by sanjacob** [comment]
You are correct that this is a new issue. I found this in the Qt changelog:

> QWebEngineProfile::defaultProfile() Has been removed.
> The default profile is now an off-the-record profile, and only used if a
> [QWebEnginePage](https://doc.qt.io/qt-6/qwebenginepage.html)
> is created without an explicit profile.
> To maintain Qt 5 like behavior, create a global profile called "Default"
> and use it when creating every
> [QWebEnginePage](https://doc.qt.io/qt-6/qwebenginepage.html).

Source: https://doc.qt.io/qt-6/qtwebengine-changes-qt6.html

**Comment by sanjacob** [comment]
Fixed, release within a day
