### ISSUE TITLE
[New University]: Mid-State Technical College

### ISSUE THREAD

**Issue by lint-os** [sanjacob/BlackboardSync#398]
### University name

Mid-State Technical College

### University abbreviation

MSTC

### University country

United States

### URL of university Blackboard instance

https://mstc.blackboard.com

### URL after logging in

https://mstc.blackboard.com/ultra/

### University network information

Name: WISCNET-BLOCK1
Description: missing
Country:

### Anything else to add?

I created this issue because the first one had the wrong url format

### License

- [X] I agree to follow this project's License

**Comment by sanjacob** [comment]
Regarding the university auto-detection, it seems that this ISP provides ip's for several other institutions:

https://www.wiscnet.net/membership

Therefore, I won't be including this feature for this college.
