### ISSUE TITLE
proposal: Parse attachments content for webdav links to more files

### ISSUE THREAD

**Issue by sanjacob** [sanjacob/BlackboardSync#92]
Some courses may be structured in a way where some or most of the contents are only listed in one of the file attachments which actually exist within webdav. To download these, extra effort must be made to check for this webdav redirection and parse such files for links.  Note that this is different from the current parsing for webdav links, as that happens within the body property of the API response, and this proposal relates to parsing the actual content of files downloaded, which means file content must be kept in memory temporarily to parse it out.

This scenario is quite rare and it isn't worth the trouble in my opinion, since the vast majority of the courses I have seen are not of this nature. However, if you would like to offer your comments on this proposal, please let me know here. If enough support for this proposal is gathered, I will consider implementing the feature.

**Comment by RobbeNooyens** [comment]
For Blackboard at the University of Antwerp, PDF files in a structure like shown below are not being downloaded. Is this related to this issue?
<img width="1058" alt="Screenshot 2023-11-14 at 16 15 30" src="https://github.com/jacobszpz/BlackboardSync/assets/42799452/c4ec7086-7373-4d58-9a43-2801af408133">
<img width="1065" alt="Screenshot 2023-11-14 at 16 15 46" src="https://github.com/jacobszpz/BlackboardSync/assets/42799452/32186285-81b5-43e7-83f6-cfa4076e127f">

**Comment by jacobszpz** [comment]
@RobbeNooyens  I'm pretty sure its not caused by this, I'll follow up on your issue
